Blockly.Msg.MPL3115A2_READ_PRESSURE_MESSAGE = "Read pressure";
Blockly.Msg.MPL3115A2_READ_PRESSURE_TOOLTIP = "";

Blockly.Msg.MPL3115A2_READ_ALTITUDE_MESSAGE = "Read altitude";
Blockly.Msg.MPL3115A2_READ_ALTITUDE_TOOLTIP = "";

Blockly.Msg.MPL3115A2_READ_TEMPERATURE_MESSAGE = "Read temperature";
Blockly.Msg.MPL3115A2_READ_TEMPERATURE_TOOLTIP = "";
