Blockly.Msg.PROXIMITY_READ_MESSAGE = "Read proximity";
Blockly.Msg.PROXIMITY_READ_TOOLTIP = "";

Blockly.Msg.PROXIMITY_READ_AMBIEANT_MESSAGE = "Read ambient";
Blockly.Msg.PROXIMITY_READ_AMBIEANT_TOOLTIP = "";
