Blockly.Msg.MPL3115A2_READ_PRESSURE_MESSAGE = "อ่านค่าความกดอากาศ";
Blockly.Msg.MPL3115A2_READ_PRESSURE_TOOLTIP = "";

Blockly.Msg.MPL3115A2_READ_ALTITUDE_MESSAGE = "อ่านค่าความสูง";
Blockly.Msg.MPL3115A2_READ_ALTITUDE_TOOLTIP = "";

Blockly.Msg.MPL3115A2_READ_TEMPERATURE_MESSAGE = "อ่านค่าอุณหภูมิ";
Blockly.Msg.MPL3115A2_READ_TEMPERATURE_TOOLTIP = "";
